### ISSUE TITLE
License: MIT or MPL possible?

### ISSUE THREAD

**Issue by gabyx** [pbenner/threadpool#2]
I respect your work and its very valubale.

Would you mind making your code licensed less restrictive in MIT oder MPL 2.0 form? Or if not then in LGPL?

Or could you grant me an LGPL License usage for Githooks https://github.com/gabyx/Githooks?

GPL3 is very restrictive, it means when using your code with MIT, it becomes automatically GPL3

Thanks for considering it.
BR

**Comment by pbenner** [comment]
Sure, that's no problem for this small library.

Best, Pb
